# Generated by Django 4.1.7 on 2023-08-18 18:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('team', models.CharField(max_length=30)),
                ('date', models.DateField(default=datetime.datetime(2023, 8, 18, 18, 41, 51, 175784))),
                ('time_in', models.TimeField(default=datetime.datetime(2023, 8, 18, 18, 41, 51, 175796))),
                ('time_out', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.IntegerField()),
                ('name', models.CharField(default='myName', max_length=30)),
                ('team', models.CharField(default='AUV', max_length=30)),
            ],
        ),
    ]
