# Generated by Django 4.1.7 on 2023-08-17 12:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('team', models.CharField(max_length=30)),
                ('date', models.DateField(verbose_name=datetime.datetime(2023, 8, 17, 12, 33, 37, 636044))),
                ('time_in', models.TimeField(verbose_name=datetime.datetime(2023, 8, 17, 12, 33, 37, 636056))),
                ('time_out', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.IntegerField()),
                ('name', models.CharField(default='myName', max_length=30)),
                ('team', models.CharField(max_length=30)),
            ],
        ),
    ]
