# Generated by Django 4.1.7 on 2023-08-17 12:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_log_date_alter_log_time_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='date',
            field=models.DateField(verbose_name=datetime.datetime(2023, 8, 17, 12, 36, 39, 181579)),
        ),
        migrations.AlterField(
            model_name='log',
            name='time_in',
            field=models.TimeField(verbose_name=datetime.datetime(2023, 8, 17, 12, 36, 39, 181591)),
        ),
    ]
