# Generated by Django 4.1.7 on 2023-07-30 15:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ind', models.IntegerField(default=0)),
                ('card_id', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('team', models.CharField(blank=True, max_length=20, null=True)),
                ('date', models.DateField(verbose_name=django.utils.timezone.now)),
                ('time_in', models.TimeField(verbose_name=django.utils.timezone.now)),
                ('time_out', models.TimeField(blank=True, null=True)),
                ('status', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('team', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
